package number4;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Window extends javax.swing.JFrame {
    
    private String[] header = new String[]{"KODE", "MATAKULIAH", "SKS", "NILAI"};
    DefaultTableModel dtm = new DefaultTableModel(header, 0);
    Mahasiswa data = null;
    File file = null;
    
    public Window() {
        initComponents();
        
        data = new Mahasiswa();
        file = new File("D:/SourceCode/Java/GUI_CRUDSederhana/src/mhmd/transkrip.csv");

        tableTranskrip.setModel(dtm);
        tableTranskrip.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = tableTranskrip.getSelectedRow();
                pilih(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelKode = new javax.swing.JLabel();
        LabelMatkul = new javax.swing.JLabel();
        LabelSKS = new javax.swing.JLabel();
        LabelNilai = new javax.swing.JLabel();
        inputanKodeTextField = new javax.swing.JTextField();
        inputanMatkulTextField = new javax.swing.JTextField();
        inputanSKSTextField = new javax.swing.JTextField();
        inputanNilaiTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TombolAdd = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        TombolUpdate = new javax.swing.JButton();
        TombolClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTranskrip = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setText("TRANSKRIP NILAI MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        LabelKode.setText("Kode");

        LabelMatkul.setText("Mata Kuliah");

        LabelSKS.setText("SKS");

        LabelNilai.setText("Nilai");

        inputanMatkulTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputanMatkulTextFieldActionPerformed(evt);
            }
        });

        inputanNilaiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputanNilaiTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelKode)
                    .addComponent(LabelMatkul)
                    .addComponent(LabelSKS)
                    .addComponent(LabelNilai))
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputanKodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(inputanMatkulTextField)
                    .addComponent(inputanSKSTextField)
                    .addComponent(inputanNilaiTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKode)
                    .addComponent(inputanKodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMatkul)
                    .addComponent(inputanMatkulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputanSKSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSKS))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputanNilaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNilai))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        TombolAdd.setText("Add");
        TombolAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolAddActionPerformed(evt);
            }
        });

        TombolDelete.setText("Delete");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        TombolUpdate.setText("Update");
        TombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpdateActionPerformed(evt);
            }
        });

        TombolClear.setText("Clear");
        TombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(TombolAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TombolDelete)
                .addGap(12, 12, 12)
                .addComponent(TombolUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TombolClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolAdd)
                    .addComponent(TombolDelete)
                    .addComponent(TombolUpdate)
                    .addComponent(TombolClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableTranskrip.setBackground(new java.awt.Color(153, 153, 255));
        tableTranskrip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE", "MATA KULIAH", "SKS", "NILAI"
            }
        ));
        jScrollPane1.setViewportView(tableTranskrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void refresh() {
        if (data != null && data.transkrip != null) {
            dtm.setRowCount(0);
            ArrayList<MataKuliah> transkrip = data.getTranskrip();
            for (int i = 0; i < transkrip.size(); i++) {
                String kode = transkrip.get(i).getKode();
                String nama = transkrip.get(i).getMatakuliah();
                int sks = transkrip.get(i).getSks();
                String nilai = transkrip.get(i).getNilai();
                Object[] baris = {kode, nama, sks, nilai};
                dtm.addRow(baris);
            }
        }
    }

    public void pilih(int row) {
        if (data != null && data.transkrip != null) {
            ArrayList<MataKuliah> transkrip = data.getTranskrip();
            inputanKodeTextField.setText(transkrip.get(row).getKode());
            inputanMatkulTextField.setText(transkrip.get(row).getMatakuliah());
            inputanSKSTextField.setText(String.valueOf(transkrip.get(row).getSks()));
            inputanNilaiTextField.setText(transkrip.get(row).getNilai());
        }
    }
    private void inputanMatkulTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputanMatkulTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputanMatkulTextFieldActionPerformed

    private void inputanNilaiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputanNilaiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputanNilaiTextFieldActionPerformed

    private void TombolAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolAddActionPerformed
        // TODO add your handling code here:
        if (data.transkrip == null) {
            data.transkrip = new ArrayList<>();
        }
        ArrayList<MataKuliah> transkrip = data.getTranskrip();
        String kode = inputanKodeTextField.getText();
        String nama = inputanMatkulTextField.getText();
        int sks = Integer.parseInt(inputanSKSTextField.getText());
        String nilai = inputanNilaiTextField.getText();
        transkrip.add(new MataKuliah(kode, nama, nilai, sks));
        TombolClearActionPerformed(evt);
        refresh();
    
    }//GEN-LAST:event_TombolAddActionPerformed

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        // TODO add your handling code here:
        ArrayList<MataKuliah> transkrip = data.getTranskrip();
        int row = tableTranskrip.getSelectedRow();
        transkrip.remove(row);
        refresh();
        TombolClearActionPerformed(evt);
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolClearActionPerformed
        // TODO add your handling code here:
        inputanKodeTextField.setText("");
        inputanMatkulTextField.setText("");
        inputanSKSTextField.setText("");
        inputanNilaiTextField.setText("");
    }//GEN-LAST:event_TombolClearActionPerformed

    private void TombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpdateActionPerformed
        // TODO add your handling code here:
        int row = tableTranskrip.getSelectedRow();
        String kode = inputanKodeTextField.getText();
        String nama = inputanMatkulTextField.getText();
        int sks = Integer.parseInt(inputanSKSTextField.getText());
        String nilai = inputanNilaiTextField.getText();
        MataKuliah mk = new MataKuliah(kode, nama, nilai, sks);
        ArrayList<MataKuliah> transkrip = data.getTranskrip();
        transkrip.set(row, mk);
        refresh();
    }//GEN-LAST:event_TombolUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelKode;
    private javax.swing.JLabel LabelMatkul;
    private javax.swing.JLabel LabelNilai;
    private javax.swing.JLabel LabelSKS;
    private javax.swing.JButton TombolAdd;
    private javax.swing.JButton TombolClear;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolUpdate;
    private javax.swing.JTextField inputanKodeTextField;
    private javax.swing.JTextField inputanMatkulTextField;
    private javax.swing.JTextField inputanNilaiTextField;
    private javax.swing.JTextField inputanSKSTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTranskrip;
    // End of variables declaration//GEN-END:variables
}
