package number2;


public class KonversiNilai extends javax.swing.JFrame {

    public KonversiNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TombolKonversiHuruf = new javax.swing.JButton();
        TombolKonversiAngka = new javax.swing.JButton();
        InputanAngka = new javax.swing.JTextField();
        LabelNilaiAngka = new javax.swing.JLabel();
        TombolClear = new javax.swing.JButton();
        LabelNilaiHuruf = new javax.swing.JLabel();
        InputanHuruf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        TombolKonversiHuruf.setText("Konversi huruf");
        TombolKonversiHuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKonversiHurufActionPerformed(evt);
            }
        });

        TombolKonversiAngka.setText("Konversi Angka");
        TombolKonversiAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKonversiAngkaActionPerformed(evt);
            }
        });

        InputanAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputanAngkaActionPerformed(evt);
            }
        });

        LabelNilaiAngka.setText("Nilai Angka");

        TombolClear.setText("Clear");
        TombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolClearActionPerformed(evt);
            }
        });

        LabelNilaiHuruf.setText("Nilai Huruf");

        InputanHuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputanHurufActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNilaiAngka)
                    .addComponent(LabelNilaiHuruf))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InputanAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(TombolKonversiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TombolClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InputanHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolKonversiAngka)))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolKonversiHuruf)
                    .addComponent(LabelNilaiAngka)
                    .addComponent(InputanAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(TombolClear)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolKonversiAngka)
                    .addComponent(InputanHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNilaiHuruf))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputanAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputanAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputanAngkaActionPerformed

    private void InputanHurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputanHurufActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_InputanHurufActionPerformed

    private void TombolKonversiHurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKonversiHurufActionPerformed
        // TODO add your handling code here:
        int nilai = Integer.parseInt(InputanAngka.getText());
        InputanHuruf.setText(nilaiHuruf(nilai));
    }//GEN-LAST:event_TombolKonversiHurufActionPerformed

    private void TombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolClearActionPerformed
        // TODO add your handling code here:
        InputanHuruf.setText("");
        InputanAngka.setText("");
    }//GEN-LAST:event_TombolClearActionPerformed

    private void TombolKonversiAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKonversiAngkaActionPerformed
        // TODO add your handling code here:
        String nilai = InputanHuruf.getText();
        InputanAngka.setText(nilaiAngka(nilai));
    }//GEN-LAST:event_TombolKonversiAngkaActionPerformed
    private String nilaiHuruf(int nilai){
        String huruf;

        if (nilai <= 100 && nilai >= 85) {
            huruf = "A";
        } else if (nilai <= 100 && nilai >= 80) {
            huruf = "A-";
        } else if (nilai <= 100 && nilai >= 75) {
            huruf = "B+";
        } else if (nilai <= 100 && nilai >= 70) {
            huruf = "B";
        } else if (nilai <= 100 && nilai >= 65) {
            huruf = "B-";
        } else if (nilai <= 100 && nilai >= 50) {
            huruf = "C";
        } else if (nilai <= 100 && nilai >= 40) {
            huruf = "D";
        } else if (nilai <= 100 && nilai >= 0) {
            huruf = "E";
        } else {
            huruf = "Nilai Tidak Valid";
        }
        return huruf;
    }
    
    private String nilaiAngka(String nilai){
        String angka;
        
        if (nilai.equalsIgnoreCase("A")) {
            angka = "85-100";
        } else if (nilai.equalsIgnoreCase("A-")) {
            angka = "80-84";
        } else if (nilai.equalsIgnoreCase("B+")) {
            angka = "75-79";
        } else if (nilai.equalsIgnoreCase("B")) {
            angka = "70-74";
        } else if (nilai.equalsIgnoreCase("B-")) {
            angka = "65-69";
        } else if (nilai.equalsIgnoreCase("C")) {
            angka = "50-64";
        } else if (nilai.equalsIgnoreCase("D")) {
            angka = "40-49";
        } else if (nilai.equalsIgnoreCase("E")) {
            angka = "0-40";
        } else {
            angka = "Huruf Tidak Valid";
        }
        return angka;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputanAngka;
    private javax.swing.JTextField InputanHuruf;
    private javax.swing.JLabel LabelNilaiAngka;
    private javax.swing.JLabel LabelNilaiHuruf;
    private javax.swing.JButton TombolClear;
    private javax.swing.JButton TombolKonversiAngka;
    private javax.swing.JButton TombolKonversiHuruf;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
